Repository usdevs/usc-website, pull requests merged in 2020-10, with the labels that each got.

#223 Updated usage of @fortawesome/react-fontawesome
  package.json
  src/components/Events/AdminEventForm.js
  src/components/Events/Calendar/Calendar.js
  src/components/Events/Calendar/DayCalendar.js
  src/components/Events/Calendar/DaySpaceCalendar.js
  src/components/Events/EditEvent.js
  src/components/Events/EventCard.js
  src/components/Events/EventForm.js
  src/components/Events/EventModal.js
  src/components/Events/Events.js
  src/components/Events/ManageEvents.js
  src/components/General/Dashboard.js
  src/components/General/FeedbackForm.js
  src/components/General/Home.js
  src/components/General/LoginModal.js
  src/components/General/Navbar.js
  src/components/Groups/CircleForm.js
  src/components/Groups/EditGroup.js
  src/components/Groups/Group.js
  src/components/Groups/GroupForm.js
  src/components/Groups/GroupGrid.js
  src/components/IntlProgs/IntlGrid.js
  src/components/IntlProgs/IntlProg.js
  src/components/IntlProgs/IntlProgForm.js
  src/components/IntlProgs/IntlProgReviewForm.js
  src/components/Modules/AddReview.js
  src/components/Modules/EditReview.js
  src/components/Modules/ManageReviews.js
  src/components/Modules/Module.js
  src/components/Modules/Modules.js
  src/components/Modules/ReviewForm.js
  src/components/Users/ProfileForm.js
  src/components/Users/Settings.js
  src/components/Users/UserCard.js
  src/components/reusable/CreateAdminEventButton.js
  src/components/reusable/CreateEventButton.js
  src/components/reusable/DeleteModal.js
  src/components/reusable/FormInputs.js
  src/components/reusable/GroupAutocomplete.js
  src/components/reusable/ImageUploader.js
  src/components/reusable/IntlProgAutocomplete.js
  src/components/reusable/MultiImageUploader.js
  src/components/reusable/UserForm.js
  src/index.js
Labels: dependencies, hacktoberfest-accepted

#226 Update PR template
  .github/pull_request_template.md
Labels: documentation

#225 Update alerts on main page
  src/components/Events/EventsAlert.js
Labels: bug, hacktoberfest-accepted

#227 Added step by step setup guide
  README.md
Labels: documentation, hacktoberfest-accepted
